unoplatform/uno.check

- .github/workflows/ci.yml
- .vscode/launch.json
- .vscode/tasks.json
- UnoCheck/Checkups/AndroidEmulatorCheckup.cs
- UnoCheck/Checkups/AndroidSdkCheckup.cs
- UnoCheck/Checkups/DotNetCheckup.cs
- UnoCheck/Checkups/OpenJdkCheckup.cs
- UnoCheck/Manifest/Manifest.cs
- UnoCheck/Manifest/Urls.cs
- gitversion.yml
> chore: adjust assembly version

- .github/workflows/ci.yml
- UnoCheck/Checkups/WSLCheckup.cs
- UnoCheck/Manifest/Manifest.cs
- manifests/uno.ui-preview.manifest.json
fixes https://github.com/unoplatform/uno.check/issues/11, fixes https://github.com/unoplatform/uno.check/issues/28, fixes https://github.com/unoplatform/uno.check/issues/14
> .NET 6 mobile preview 13

- .github/workflows/ci.yml
- UnoCheck/UnoCheck.csproj
> fix: Include shims for package signing

- manifests/uno.ui-preview.manifest.json
> feat: Add support for installing arm64 dotnet runtime

- UnoCheck/Checkups/XCodeCheckup.cs
GitHub Issue (If applicable): closes #71   
- Feature
uno-check fails silently when Xcode is not installed
The uno-check will use "xcode-select", "--install" to install the 
> fix: uno-check fails silently when Xcode is not installed

- UnoCheck/Checkups/GitCliInstalledCheckup.cs
- UnoCheck/Checkups/WindowsPhytonInstallationCheckup.cs
- UnoCheck/Solutions/GitCliSolution.cs
- UnoCheck/Solutions/LinuxGitCliSolution.cs
- UnoCheck/Solutions/LinuxOtherDistGitCliSolution.cs
- UnoCheck/Solutions/MacGitCliSolution.cs
GitHub Issue (If applicable): closes #84   
- Feature
There is no check to Git Cli presence on Linux, macOS, and Windows.
The uno-check will validate the presence of git cli.
> feat: Add a check to validate the presence of git

- UnoCheck/Checkups/WindowsPythonInstallationCheckup.cs
- UnoCheck/Solutions/PythonIsInstalledSolution.cs
Fixed incorrect spelling of Python (Pyton)
> Fixed spelling of Pyton (Python)

- UnoCheck/Checkups/AndroidEmulatorCheckup.cs
This PR makes sure that `uno-check` will install the Android Emulator for arm64.
-Fixes #97
> Added a fallback for arm Cpus

- UnoCheck/Manifest/Manifest.cs
- manifests/uno.ui-preview-major.manifest.json
closes https://github.com/unoplatform/uno.check/issues/139
> ci: Bump to preview 2

- UnoCheck/Icon.cs
- UnoCheck/ToolInfo.cs
- Adjust icons for setup
- Adjust android emulator setup
> Misc linux updates

- UnoCheck/Solutions/DotNetSdkScriptInstallSolution.cs
fixes https://github.com/unoplatform/uno.check/issues/257
> fix: Use sudo for .NET install on linux

- .github/workflows/ci.yml
- UnoCheck/CheckCommand.cs
- UnoCheck/CheckSettings.Uno.cs
- UnoCheck/Checkups/UnoSdkCheckup.cs
This will allow uno.check to install the uno.sdk version needed by the solution when integrating ith IDE's
> feat: Add parameter to allow passing Uno.SDK version required by solution

- UnoCheck/CheckCommand.cs
- UnoCheck/Icon.cs
- UnoCheck/Telemetry/TelemetryClient.cs
- UnoCheck/Util.cs
closes https://github.com/unoplatform/uno.check/issues/346
> fix: Show the skipped checks reasons

- doc/configuring-uno-check.md
- doc/troubleshooting-uno-check.md
Here are some minor adjustments for the uno.check documentation to make sure it properly displays with docfx on the doc website.
> Minor adjustments for the uno.check documentation

- manifests/uno.ui-preview-major.manifest.json
- manifests/uno.ui-preview.manifest.json
- manifests/uno.ui.manifest.json
Bump xCode to 16.3, which is the latest xcode version
> chore: bump xcode to 16.3

- UnoCheck/Checkups/DotNetCheckup.cs
- UnoCheck/Checkups/DotNetWorkloadsCheckup.cs
- UnoCheck/Checkups/VSRestartCheckup.cs
- UnoCheck/Checkups/VSRestartCheckupContributor.cs
- UnoCheck/Models/StateKey.cs
- UnoCheck/Program.cs
- UnoCheck/Solutions/MsInstallerSolution.cs
> feat: Add Checkup to notify to restart VS when .NET SDK\workloads are updated

- UnoCheck/ToolUpdater.cs
- install_locally.sh
closes https://github.com/unoplatform/uno.check/issues/405
> fix: macOS and linux autoupdater script

- UnoCheck/UnoCheck.csproj
I feel like this stuff been left over from the maui-check times and i don't think we need it anymore.
> chore: remove unused code

- manifests/uno.ui-preview-major.manifest.json
- manifests/uno.ui-preview.manifest.json
- manifests/uno.ui.manifest.json
**GitHub Issue:** closes https://github.com/unoplatform/private/issues/897
- 🐞 Bugfix
> chore: bump xcode check to 16.4

- UnoCheck/Checkups/XCodeCheckup.cs
**GitHub Issue:** closes https://github.com/unoplatform/private/issues/897
- 🎨 Code style update (formatting)
> chore: update xcode check wording

- UnoCheck/Checkups/XCodeCheckup.cs
**GitHub Issue:** closes https://github.com/unoplatform/private/issues/897
- 🐞 Bugfix
> Fix xcode ios sdk validation
