UnoCheck/AndroidSdk/Avd.cs
fix: Changed From method to get the AVD name from the config.ini
Reorganized the `From` method to extract the name of the AVD from the config.ini so that the *`<avd_name>.ini`* could be built.
Refs: #20
=> fix: Changed From method to get the AVD name from the config.ini

UnoCheck/AndroidSdk/Avd.cs
The **AvdId** property in doesn't seem to be around anymore in .android\avd\pixel5-_api_30.ini, that is used to set **Avd.Name** .
Keep doing it as before, and if that key doesn't exist, then replace _.avd_ by _.ini_ as per the folder structure:
=> Get Avd configuration out of the folder name

UnoCheck/Checkups/WindowsLongPathCheckup.cs, UnoCheck/Program.cs, UnoCheck/Solutions/LongPathsNotEnabledSolution.cs
GitHub Issue (If applicable): closes #81 
- Feature
This is a longstanding issue affecting Win32.
The uno-check will apply the registry changes.
=> feat: add validation for long path support on windows

UnoCheck/Checkups/WindowsPhytonInstallationCheckup.cs, UnoCheck/Program.cs, UnoCheck/Solutions/PytonIsInstalledSolution.cs
GitHub Issue (If applicable): closes #82 
- Feature
There is no check to Python presence on Windows.
The uno-check will validate the presence of python.
=> feat: Add validation for the presence of python

UnoCheck/Checkups/HyperVCheckup.cs, UnoCheck/Program.cs, UnoCheck/Solutions/HyperVActivationSolution.cs, UnoCheck/UnoCheck.csproj
GitHub Issue (If applicable): closes #46 
- Feature
There is no check to Hyper-V activation on Windows.
The uno-check will validate the presence of Hyper-V and install if required.
=> feat: Add validation for Hyper-V on Windows

UnoCheck/Checkups/OpenJdkCheckup.cs, manifests/uno.ui-preview.manifest.json, manifests/uno.ui.manifest.json
The wrong arch (x64) was downloaded.
The same fix should also work for Windows and eventually Linux (not part of the manifest) based on the packages names from https://learn.microsoft.com/en-us/java/openjdk/older-releases#openjdk-11
Also bump the version so binaries for arm64 are available to download.
=> fix: installation of OpenJDK for macos-arm64

UnoCheck/CheckCommand.cs, UnoCheck/UnoCheck.csproj
=> feat: Support case-insensitive prompts

manifests/uno.ui-preview-major.manifest.json, manifests/uno.ui-preview.manifest.json, manifests/uno.ui.manifest.json
=> fix: Migrate to primary download urls for non-ci installs

.github/workflows/ci.yml, UnoCheck/CheckSettings.Uno.cs, UnoCheck/TargetPlatform.cs, UnoCheck/TargetPlatformHelper.cs, manifests/uno.ui-preview-major.manifest.json, manifests/uno.ui-preview.manifest.json, manifests/uno.ui.manifest.json
Universal Windows Platform development tools represent a fairly significant dependency, which may be an obstacle to quickly getting started with Uno development.
Fortunately, the dependencies on our getting started documentation were recently updated to match the Microsoft-endorsed workloads for Windows App SDK.  Accordingly, we advise new users to run the `uno-check` tool to pull down the required workloads if they're missing. 
This PR updates our tool to no longer assume UWP workload is needed: matching the docs. It does this by using the workload ids which Microsoft details in its getting started with WASDK docs. This change is _not_ breaking because it maintains compatibility with the previous target platform strings: "win32" and "win32desktop".
=> feat(vswindows): Add WASDK workloads to match docs

.github/workflows/ci.yml, UnoCheck/Manifest/Manifest.cs, UnoCheck/Solutions/MsInstallerSolution.cs, manifests/uno.ui-preview.manifest.json, manifests/uno.ui.manifest.json
closes https://github.com/unoplatform/uno.check/issues/168
=> fix: Don't fail on more recent .NET installed version for windows

UnoCheck/Checkups/XCodeCheckup.cs, UnoCheck/Solutions/XcodeEulaSolution.cs
Fix https://github.com/unoplatform/uno.check/issues/170
The EULA is not displayed on CI, when `--ci` is specified.
=> feat: Add check and solution for Xcode EULA

UnoCheck/Checkups/XCodeCheckup.cs, manifests/uno.ui-preview-major.manifest.json, manifests/uno.ui-preview.manifest.json, manifests/uno.ui.manifest.json
* Fix the manifest (inverted version/name)
* Update preview manifest with Xcode 15
* Parse the correct string to retrive the Xcode version from `Info.plist`
* On success show the installed Xcode version (and not the one specified in the manifest). That can be confusing if `minimum` is used in the manifest files
=> fix: Fix Xcode version checks and manifests

UnoCheck/Checkups/AndroidSdkCheckup.cs
This avoid downloading multiple files (one per arch) where the last one will be decompressed over the previous. E.g. ending up having `emulator` as a `arm64` binary on an `x86` Mac.
Previous verbose logs showed:
```
...
– Downloading https://dl.google.com/android/repository/emulator-darwin_x64-10696886.zip ...
– Downloading https://dl.google.com/android/repository/emulator-darwin_aarch64-10696886.zip
...
```
=> fix(androidsdk): only download arch independent or matching the host archives

manifests/uno.ui-preview-major.manifest.json, manifests/uno.ui-preview.manifest.json, manifests/uno.ui.manifest.json
This PR adds the Winarm64 Urls for the dotnetSDK.  We were falling back to the Win64 and for some reason those are not longer installing the SDKs on Arm-based PCs.
Tested with these two Urls:
https://dotnetcli.azureedge.net/dotnet/Sdk/7.0.403/dotnet-sdk-7.0.403-win-arm64.exe
https://dotnetcli.azureedge.net/dotnet/Sdk/8.0.100/dotnet-sdk-8.0.100-win-arm64.exe
related to https://github.com/unoplatform/uno.check/issues/200
=> chore: add winarm64 dotnet sdk urls

UnoCheck/Checkups/DotNetNewUnoTemplatesCheckup.cs
fixes https://github.com/unoplatform/uno.check/issues/212
=> fix: Ensure dotnet template uses en culture for parsing the output

doc/using-uno-check.md
I fixed the code sample for uninstalling the .NET workload. It needs to be `--all` and not `-all`.
=> Fixed CLI parameter for dotnet workload command

UnoCheck/Checkups/HyperVCheckup.cs, UnoCheck/Checkups/WindowsLongPathCheckup.cs, UnoCheck/Checkups/WindowsPythonInstallationCheckup.cs
Duplicated **Checkup** words for some checkups for uno-check
No more duplicated **Checkup** words
=> chore: Update checkups files to remove duplicate checkup word

UnoCheck/Properties/launchSettings.json
Previously the path was hardcoded which would give you an error when trying to run the program
=> fix: Do not hardcode path in launchsettings.json

UnoCheck/Checkups/DotNetNewUnoTemplatesCheckup.cs
The problem was that when we were parsing the version of uno.templates the result in some cases was like -"5.3.96/r" where /r would reset the caret to the start of the line. So the result was messed up. Now we are trimming all the whitespace characters from the version string. Also fixed the typo
Fixes #236 
Fixes #277
=> fix: Incorrect output from DotNetNewUnoTemplatesCheckup

UnoCheck/Checkups/XCodeCheckup.cs
Fixes https://github.com/unoplatform/uno.check/issues/279
`xcodebuild` will fail [1] and the error can be confusing to people running `uno-check`.
[1] it fails because there's no Xcode project to run, which is normal, but it fails **differently** when the EULA was not accepted - which is what we're looking for,
=> fix: do not display output when running xcodebuild

.github/workflows/ci.yml, UnoCheck.Tests/CheckCommandTests.cs, UnoCheck.Tests/UnoCheck.Tests.csproj, UnoCheck.sln, UnoCheck/CheckCommand.cs, UnoCheck/CheckSettings.Uno.cs, UnoCheck/Checkups/DotNetWorkloadsCheckup.cs, UnoCheck/UnoCheck.csproj
The idea behind that feature is to parse the TFM's and transform them into the TargetPlatforms since we already have all the needed infra for that. So now we can just pass the TFM's from the IDE's with `--tfm mytfm`  and add `--ci --non-interactive` just to get the read-only output and uno-check could probably be used for the IDE integration after that.
Fixes #286
=> feat: Add TFM based checks

UnoCheck/Solutions/DotNetSdkScriptInstallSolution.cs
The latest update of dotnet-install.sh explicitly uses bash options
=> fix: Use bash on macos

version.json
This is an automated version bump of the  **main** branch after the creation of the release branch release/stable/1.28, based on #329
=> Version bump after 1.28 release branch

UnoCheck/CheckCommand.cs, UnoCheck/Util.cs
This PR updates check skips according to https://github.com/unoplatform/private/issues/506
Git\Ninja\Powershell\Python are always disabled when --tfm isn't specified and when tfm is not net8.0 based.
When uno.check is called from IDE we now only skip "vswin","vswinworkloads" for all IDE's. Logic related to the "dotnet new" check will be added in each IDE code separately
=> fix: Update skips logic

version.json
This will allow uno.check to install the uno.sdk version needed by the solution when integrating ith IDE's
This is an automated version bump of the  **main** branch after the creation of the release branch release/stable/1.29, based on #337
=> Version bump after 1.29 release branch

UnoCheck/TargetPlatformHelper.cs, doc/configuring-uno-check.md
Second try, somehow it did just closed #344 
So again:
- Reordered the case statements so the same result groups for brevity
- fixed the `windows` case to match the to be expected result! So far it had been pointing to TargetPlatform.WindowsAppSDK instead of its logical result of TargetPlatform.Windows.
- added the case `winappsdk` as alternative to the current `wasdk`, because of the existing `wasdk` could/can be mistaken with the `wasm` as the actual WebAssembly target. For those who are not common with the shortcuts of target names this current one has been a potentional problem source. Remark: I did not remove the `wasdk` !
- telling about its the available options including above mentioned ones
- added a note explicitly telling to use the `--target` as prefix before each of the …
=> Docs(targetplatforms):Updated Target Plattforms

version.json
This is an automated version bump of the  **main** branch after the creation of the release branch release/stable/1.30, based on #350
=> Version bump after 1.30 release branch

UnoCheck/Checkups/XCodeCheckup.cs
fixes #172
This pull request introduces a new validation step to ensure the iOS SDK is installed when examining the Xcode setup. 
* Added a check in `public override Task<DiagnosticResult> Examine(SharedState history)` to validate the presence of the iOS SDK and provide instructions if it is missing.
* Introduced a new method `ValidateForiOSSDK(XCodeInfo selected)` to encapsulate the logic for checking the iOS SDK installation.
=> feat(iOS): check for SDK

UnoCheck/Checkups/XCodeCheckup.cs
Fix iOS SDK validation. Previous validation would give false positives when different iOS simulators were installed.
=> fix: iOS SDK check avoiding false positive

UnoCheck/ConsoleWindowHelper.cs, UnoCheck/Program.cs
I can't repro that issue on my machine, i guess it might be specific to some Windows version. But this might fix the issue. Requires testing
Fixes https://github.com/unoplatform/uno.studio/issues/782
=> fix: Ensure uno-check window appears on-top

UnoCheck/ConsoleWindowHelper.cs
=> fix: pop a window in Z‑order without making it always‑on‑top

UnoCheck/Program.cs
More info - https://github.com/unoplatform/uno.check/issues/340#issuecomment-2849118302
Also removes the mentioning of "acquirepackages" since i don't think it exists anymore as a command.
Thanks @DevTKSS for finding that! Could you give it a test?
=> fix: "No such command" when typing uno-check check

UnoCheck/CheckCommand.cs, UnoCheck/Checkups/HttpsDevCertCheckup.cs, UnoCheck/Program.cs, UnoCheck/Util.cs
This checkup is available if one of the targets is WASM.
It runs `dev-certs https -c -t` to check for trusted certs and `dev-certs https --trust` to fix.
Fixes #375
=> feat: Add checkup to trust https dev certs

UnoCheck.Tests/LaunchSettingsTests.cs, UnoCheck/Properties/launchSettings.json
This PR fixes the launchsettings.json once more, without that PR i can't run the uno.check. Also adding some regression test for launchsettings.json verifying that it's valid
=> fix: launchSettings.json and add regression test
